initial_assessment:
  description: >
    Conduct an initial assessment of the student based on their profile and interactions. 
    Student ID: {student_id}
    Year: {year}
    Major: {major}
    Current GPA: {gpa}
    Input: {input}
    
    Consider their academic background, interests, challenges, and emotional state.
    Identify any immediate concerns or areas that need attention.
    Provide a comprehensive assessment report that covers academic performance, 
    well-being, career alignment, and recommended support strategies.
  expected_output: >
    A comprehensive initial assessment report including:
    1. Student profile summary
    2. Academic analysis (performance, study patterns, strengths, and areas for improvement)
    3. Well-being assessment
    4. Career alignment evaluation
    5. Recommended support strategies
    6. Suggested follow-up actions
  agent: mentor
  output_file: "student_reports/{student_id}/initial_assessment.md"

academic_planning:
  description: >
    Create an academic plan for the student based on their profile and goals.
    Student ID: {student_id}
    Year: {year}
    Major: {major}
    Current GPA: {gpa}
    Input: {input}
    
    Consider their current academic standing, career goals, and interests.
    Identify courses, resources, and opportunities that align with their goals.
    Provide a detailed academic plan with short-term and long-term objectives.
  expected_output: >
    A detailed academic plan including:
    1. Course recommendations for upcoming terms
    2. Study strategies based on learning style
    3. Resource recommendations (tutoring, workshops, etc.)
    4. Extracurricular activities relevant to career goals
    5. Timeline with key milestones and checkpoints
    6. Strategies to improve academic performance if needed
  agent: academic_advisor
  output_file: "student_reports/{student_id}/academic_plan.md"

well_being_assessment:
  description: >
    Assess the student's emotional and psychological well-being based on their interactions.
    Student ID: {student_id}
    Year: {year}
    Major: {major}
    Current GPA: {gpa}
    Input: {input}
    
    Analyze their emotional tone, identify any signs of distress or anxiety,
    and evaluate their overall well-being and stress management.
    Provide appropriate support, resources, and coping strategies.
  expected_output: >
    A well-being assessment report including:
    1. Emotional state analysis
    2. Identified stressors and challenges
    3. Coping strategy recommendations
    4. Campus resources for support
    5. Follow-up plan if needed
    6. Safety assessment (if applicable)
  agent: counselor
  output_file: "student_reports/{student_id}/wellbeing_assessment.md"

progress_monitoring:
  description: >
    Review the student's progress since the last interaction and update their support plan.
    Student ID: {student_id}
    Year: {year}
    Major: {major}
    Current GPA: {gpa}
    Previous Reports: {previous_reports}
    Input: {input}
    
    Compare current status with previous assessments, identify improvements or new challenges,
    and adjust support strategies accordingly.
    Provide an updated assessment and recommendations.
  expected_output: >
    A progress monitoring report including:
    1. Comparison with previous assessments
    2. Noted improvements or new challenges
    3. Updated support strategies
    4. Revised goals and timeline
    5. Recommended next steps
  agent: mentor
  output_file: "student_reports/{student_id}/progress_report.md"

emergency_response:
  description: >
    Respond to a student in distress or crisis. This is a high-priority assessment.
    Student ID: {student_id}
    Year: {year}
    Major: {major}
    Current GPA: {gpa}
    Input: {input}
    
    Quickly assess the severity of the situation, identify immediate safety concerns,
    and provide appropriate crisis response guidance.
    Emphasize campus emergency resources and immediate steps for safety.
  expected_output: >
    An emergency response report including:
    1. Crisis severity assessment
    2. Immediate safety recommendations
    3. Campus emergency resources
    4. Follow-up plan
    5. Documentation of concerns
  agent: counselor
  output_file: "student_reports/{student_id}/emergency_response.md"